// <auto-generated />
using System;
using Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230706203939_setstatusvalidation")]
    partial class setstatusvalidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domains.Entities.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Governorate")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("TicketStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = 1,
                            CreationDateTime = new DateTime(2023, 7, 5, 23, 39, 39, 67, DateTimeKind.Local).AddTicks(8524),
                            Description = "Lorem ipsum dolor sit amet",
                            District = "Nasr City",
                            Governorate = 5,
                            PhoneNumber = "1234567890",
                            TicketStatus = 1
                        },
                        new
                        {
                            ID = 2,
                            City = 0,
                            CreationDateTime = new DateTime(2023, 7, 4, 23, 39, 39, 67, DateTimeKind.Local).AddTicks(8572),
                            Description = "Consectetur adipiscing elit",
                            District = "Roushdy",
                            Governorate = 0,
                            PhoneNumber = "9876543210",
                            TicketStatus = 0
                        },
                        new
                        {
                            ID = 3,
                            City = 2,
                            CreationDateTime = new DateTime(2023, 7, 3, 23, 39, 39, 67, DateTimeKind.Local).AddTicks(8578),
                            Description = "Sed do eiusmod tempor incididunt",
                            District = "Dokki",
                            Governorate = 10,
                            PhoneNumber = "5555555555",
                            TicketStatus = 0
                        },
                        new
                        {
                            ID = 4,
                            City = 3,
                            CreationDateTime = new DateTime(2023, 7, 2, 23, 39, 39, 67, DateTimeKind.Local).AddTicks(8582),
                            Description = "Ut labore et dolore magna aliqua",
                            District = "Luxor City",
                            Governorate = 13,
                            PhoneNumber = "9999999999",
                            TicketStatus = 1
                        },
                        new
                        {
                            ID = 5,
                            City = 5,
                            CreationDateTime = new DateTime(2023, 7, 1, 23, 39, 39, 67, DateTimeKind.Local).AddTicks(8586),
                            Description = "Excepteur sint occaecat cupidatat non proident",
                            District = "Asyut Center",
                            Governorate = 2,
                            PhoneNumber = "1111111111",
                            TicketStatus = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
